In [1]:
import numpy as np
import numpy.random as rd

## 1. Préliminaires : manipulations de matrices
### 1.1 Construire une matrice carrée aléatoire A
Utiliser `rd.randint(10)` (entiers entre 0 et 9) ou `rd.rand()` (flottants dans [0,1)).

Fixer un seed pour obtenir des résultats reproductibles, par exemple `np.random.seed(42)`.


In [2]:
np.random.seed(42) # Reproductibilité

SIZE = 4

def randomMatrix(n):
    return rd.randint(10, size=(n,n))

A = randomMatrix(SIZE)

print(A)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]


### 1.2 Extraire la partie triangulaire inférieure
À partir de A, construire T triangulaire inférieure (diagonale incluse).


In [3]:
# Lower
T = np.tril(A)

print(T)

[[6 0 0 0]
 [6 9 0 0]
 [7 4 3 0]
 [7 2 5 4]]


In [4]:
# Upper
U = np.triu(A)

print(U)

[[6 3 7 4]
 [0 9 2 6]
 [0 0 3 7]
 [0 0 0 4]]


### 1.3 Construire une matrice diagonale de 2
Construire explicitement la matrice `D = 2I_n` (des 2 sur la diagonale principale et 0 ailleurs),
par exemple à partir de `np.eye(n, n)`.


In [5]:
D = 2 * np.eye(SIZE)

print(D)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


### 1.4 Décaler la diagonale
Ici, "décaler la diagonale" signifie placer les 1 de `np.eye()` sur une autre diagonale que la diagonale principale.
Tester `k=1`, `k=2` (sur-diagonales) et `k=-1`, `k=-2` (sous-diagonales), puis observer la structure obtenue.


In [6]:
print(np.eye(SIZE, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [7]:
print(np.eye(SIZE, k=2))

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
print(np.eye(SIZE, k=-1))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [9]:
print(np.eye(SIZE, k=-2))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### 1.5 Construire une matrice non carrée B
Utiliser `np.ones([n, k])`.


In [10]:
B = np.ones([2, 4])

print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 1.6 Récupérer les dimensions de la matrice B
Utiliser `np.shape(B)`.


In [11]:
shape = np.shape(B)

print(shape)

(2, 4)


### 1.7 Récupérer le nombre de lignes de la matrice B


In [12]:
# Nombre de lignes
print(shape[0])

2


In [13]:
# Nombre de colonnes
print(shape[1])

4


### 1.8 Construire un vecteur aléatoire de taille n avec une boucle `for`


In [14]:
np.random.seed(42) # Reproductibilité

def randomVector(n):
    v = np.zeros(n)
    for i in range(n): v[i] = rd.randint(10)
    return v

C = randomVector(5)

print(C)

[6. 3. 7. 4. 6.]


### 1.9 Parcourir une boucle `for` à l'envers
Construire le vecteur d'entiers `[n-1, ..., 1, 0]`.


In [15]:
def reverseRandomVector(n):
    v = np.zeros(n)
    for i in range(n - 1, -1, -1): v[i] = n - i - 1
    return v

E = reverseRandomVector(5)

print(E)

[4. 3. 2. 1. 0.]


### 1.10 Explorer la factorisation LU dans SciPy
Rechercher dans `scipy.linalg` la fonction LU et expliquer l'intérêt de ses paramètres principaux.


In [16]:
import scipy.linalg as sla

In [17]:
help(sla.lu)

Help on function lu in module scipy.linalg._decomp_lu:

lu(a, permute_l=False, overwrite_a=False, check_finite=True, p_indices=False)
    Compute LU decomposition of a matrix with partial pivoting.

    The decomposition satisfies::

        A = P @ L @ U

    where ``P`` is a permutation matrix, ``L`` lower triangular with unit
    diagonal elements, and ``U`` upper triangular. If `permute_l` is set to
    ``True`` then ``L`` is returned already permuted and hence satisfying
    ``A = L @ U``.

    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non-termination) if

La fonction `sla.lu` prend 1 paramètre obligatoire, et 3 paramètres optionnels : 

Paramètre principal

- `a` : correspond à la matrice $A$ passée en paramètre pour procéder à la décomposition

Paramètres optionnels

- `permute_l` : qui permet d'effectuer ou non la multiplication `PL`
- `overwrite_a` : qui permet d'écraser la matrice en paramètre par sa décomposition (peut améliorer les performance)
- `check_finite` : qui permet de vérifier que la matrice passée en paramètre contient uniquement des nombres fini de nombres

### 1.11 Permuter deux lignes d'une matrice
Effectuer des permutations deux à deux et vérifier le résultat. On pourra utiliser la notation `B[[i1,i2],:]` pour désigner la matrice extraite de B composée des lignes `i1` et `i2`.

In [18]:
def permute(M,  i1, i2):
    if (i1 > shape[0] - 1 or i2 > shape[1] - 1):
        return M
        
    M[[i1, i2], :] = M[[i2, i1], :]
    return M


np.random.seed(42)

B = randomMatrix(4)

print(B)

B = permute(B, 0, 3) # Première et dernière ligne

print(B)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]
[[7 2 5 4]
 [6 9 2 6]
 [7 4 3 7]
 [6 3 7 4]]


Utiliser `np.argmax()` pour trouver l'indice du plus fort coefficient dans un tableau en valeur absolue

In [19]:
print(A)
print("Indice de la valeur maximale: ", np.argmax(np.abs(A)))

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]
Indice de la valeur maximale:  5


## 2. Système triangulaire inférieur : descente (forward)
### 2.1 Rappeler la condition nécessaire et suffisante d'inversibilité
Pour une matrice triangulaire, expliciter la condition sur la diagonale.


Il ne faut pas que la matrice ait des $0$ sur la diagonale ($M_{ii} \neq 0$)

### 2.2 Coder `Descente(L, b)`
`L` est triangulaire inférieure inversible et `b` est le second membre.
La fonction retourne la solution `x` de `Lx=b`.


In [20]:
def Descente(L, b):
    for i in range(np.shape(L)[0]):
        if L[i][i] == 0:
            raise ValueError("La matrice L n'est pas inversible")

    n = len(b)
    x = np.zeros(n)

    for i in range(n):
        somme = 0
        for j in range(i):
            somme += L[i][j] * x[j]

        x[i] = (b[i] - somme) / L[i][i]
    
    return x

### 2.3 Tester `Descente()`


Construire un cas de test complet à partir d'une matrice `L` et d'un vecteur `b`.


Étape A : construire une matrice `L` triangulaire inférieure (ou réutiliser celle du début du TP).


In [21]:
np.random.seed(42)

L = randomMatrix(SIZE)
L = np.tril(L) # Triangulaire inférieur

print(L)

[[6 0 0 0]
 [6 9 0 0]
 [7 4 3 0]
 [7 2 5 4]]


Étape B : construire un vecteur `b` aléatoire de dimension `n`.


In [22]:
np.random.seed(42)

b = randomVector(SIZE)

print(b)

[6. 3. 7. 4.]


Étape C : résoudre `Lx=b` avec votre fonction `Descente`.


In [23]:
x = Descente(L, b)

# devrait donner b
print("vérification: ", L @ x)
print("b initial: ", b)

vérification:  [6. 3. 7. 4.]
b initial:  [6. 3. 7. 4.]


Étape D : comparer avec `scipy.linalg` pour valider le résultat numériquement.


In [24]:
print(Descente(L, b) == sla.solve(L, b))

# devrait être les mêmes valeurs
print(Descente(L, b))
print(sla.solve(L, b))

[ True  True  True  True]
[ 1.         -0.33333333  0.44444444 -1.13888889]
[ 1.         -0.33333333  0.44444444 -1.13888889]


## 3. Système triangulaire supérieur : montée (backward)
### 3.1 Coder `Montee(U, b)`
`U` est triangulaire supérieure inversible et `b` est le second membre.


In [25]:
def Montee(U, b):
    for i in range(np.shape(U)[0]):
        if U[i][i] == 0:
            raise ValueError("La matrice U n'est pas inversible")

    n = len(b)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        somme = 0
        for j in range(i + 1, n):
            somme += U[i][j] * x[j]

        x[i] = (b[i] - somme) / U[i][i]
    
    return x

### 3.2 Tester `Montee()` sur un système `Ux=y`


In [26]:

np.random.seed(42)

U = randomMatrix(SIZE)
U = np.triu(U) # Triangulaire supérieur

print(U)

[[6 3 7 4]
 [0 9 2 6]
 [0 0 3 7]
 [0 0 0 4]]


In [27]:

np.random.seed(42)

y = randomVector(SIZE)

print(y)

[6. 3. 7. 4.]


In [28]:
x = Montee(U, y)

# devrait donner b
print("vérification: ", U @ x)
print("y initial: ", y)

vérification:  [6. 3. 7. 4.]
y initial:  [6. 3. 7. 4.]


Comparer votre résultat avec `scipy.linalg` pour vérifier la solution.


In [29]:

print(Montee(U, y) == sla.solve(U, y))

# devrait être les mêmes valeurs
print(Montee(U, y))
print(sla.solve(U, y))

[ True  True  True  True]
[ 0.5        -0.33333333  0.          1.        ]
[ 0.5        -0.33333333  0.          1.        ]


## 4. Factorisation LU
Dans chaque sous-partie, vérifier vos fonctions sur un exemple numérique en contrôlant l'erreur.


### 4.1 Version basique sans pivot (pas in place)
#### 4.1.1 Coder `MonLU(A)`
`A` est carrée. La fonction retourne `L` et `U` avec diagonale de `L` égale à 1.
Remarque : cette version peut échouer si un pivot est nul (ou très petit).


In [30]:
def MonLU(A):
    n = A.shape[0]
    
    L = np.eye(n) # I
    U = np.zeros((n, n))
    
    for i in range(n):
        # Calcul de U (ligne i)
        for j in range(i, n):
            somme = 0
            for k in range(i):
                somme += L[i][k] * U[k][j]
            U[i][j] = A[i][j] - somme
        
        # Calcul de L (colonne i)
        for j in range(i + 1, n):
            somme = 0
            for k in range(i):
                somme += L[j][k] * U[k][i]
            
            if U[i][i] == 0:
                raise ValueError("Pivot nul, échec de LU sans pivot")
            
            L[j][i] = (A[j][i] - somme) / U[i][i]
    
    return L, U

Vérifier la décomposition sur un exemple de matrice carrée (`A` et `L@U`).


In [85]:
np.random.seed(42)

A = randomMatrix(4) 
print(A, "\n")

L, U = MonLU(A)

print(L @ U)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]] 

[[6. 3. 7. 4.]
 [6. 9. 2. 6.]
 [7. 4. 3. 7.]
 [7. 2. 5. 4.]]


#### 4.1.2 Écrire `SolveLU(A, b)`
La fonction retourne `x` en utilisant successivement descente puis montée.


In [32]:
def SolveLU(A, b):
    L, U = MonLU(A)
    y = Descente(L, b)
    x = Montee(U, y)
    return x

Tester `SolveLU` sur un système aléatoire `Ax=b`.


In [33]:
np.random.seed(42)

A = randomMatrix(SIZE)
b = randomVector(SIZE)

print("A: \n", A)
print("b: \n", b)

A: 
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]]
b: 
 [1. 7. 5. 1.]


In [34]:
x = SolveLU(A, b)
print("x: \n", x)

x: 
 [-0.21179625  0.45308311 -0.33243968  0.80965147]


In [87]:
# devrait donner b
print("vérification: ", A @ x)
np.allclose(A @ x, b)

vérification:  [1. 7. 5. 1.]


True

### 4.2 Version in place sans pivot


#### 4.2.1 Coder `MonLUInPlace(A)`
La fonction retourne `N` (in place) tel que `N = (L-I) + U` avec `A=LU` et diag(`L`)=1.


In [88]:
def MonLUInPlace(A):
    n = A.shape[0]
    N = A.copy().astype(float)
    
    for i in range(n):
        # Calcul de U (ligne i)
        for j in range(i, n):
            somme = 0
            for k in range(i):
                somme += N[i][k] * N[k][j]
            N[i][j] = N[i][j] - somme
        
        # Vérification pivot
        if N[i][i] == 0:
            raise ValueError("Pivot nul, échec de LU sans pivot")
        
        # Calcul de L (colonne i)
        for j in range(i + 1, n):
            somme = 0
            for k in range(i):
                somme += N[j][k] * N[k][i]
            
            N[j][i] = (N[j][i] - somme) / N[i][i]
    
    return N

#### 4.2.2 Écrire `ExtractLU(N)`
Extraire `L` et `U` depuis `N`, avec ajout des 1 sur la diagonale de `L`.


In [90]:
def ExtractLU(N):
    n = N.shape[0]
    L = np.eye(n) + np.tril(N, k=-1) # Diagonale = 1
    U = np.triu(N)
    return L, U

Vérifier la décomposition in place sur un exemple de matrice carrée.


In [92]:
np.random.seed(42)

A = randomMatrix(SIZE)
print("A: \n", A, "\n")

N = MonLUInPlace(A)
print("N (L-U in place): \n", N, "\n")

L, U = ExtractLU(N)
print("L: \n", L, "\n")
print("U: \n", U, "\n")

A: 
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]] 

N (L-U in place): 
 [[ 6.          3.          7.          4.        ]
 [ 1.          6.         -5.          2.        ]
 [ 1.16666667  0.08333333 -4.75        2.16666667]
 [ 1.16666667 -0.25        0.92982456 -2.18128655]] 

L: 
 [[ 1.          0.          0.          0.        ]
 [ 1.          1.          0.          0.        ]
 [ 1.16666667  0.08333333  1.          0.        ]
 [ 1.16666667 -0.25        0.92982456  1.        ]] 

U: 
 [[ 6.          3.          7.          4.        ]
 [ 0.          6.         -5.          2.        ]
 [ 0.          0.         -4.75        2.16666667]
 [ 0.          0.          0.         -2.18128655]] 



#### 4.2.3 Résoudre un système linéaire à l'aide de `MonLUInPlace()`.


In [93]:
print("L @ U: \n", L @ U, "\n")
print("A: \n", A, "\n")

L @ U: 
 [[6. 3. 7. 4.]
 [6. 9. 2. 6.]
 [7. 4. 3. 7.]
 [7. 2. 5. 4.]] 

A: 
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]] 



### 4.3 Version in place avec pivot partiel (permutations)


#### 4.3.1 Coder `MonLUPivot(A)`
La fonction retourne `N` (in place) et `P`, matrice de permutation, telles que `PA = LU`.


In [117]:
def MonLUPivot(A):
    n = A.shape[0]
    N = A.copy().astype(float)
    P = np.eye(n) # Permutation
    
    for i in range(n):
        # Pivot partiel
        pivot_index = np.argmax(np.abs(N[i:, i])) + i
        if N[pivot_index][i] == 0:
            raise ValueError("Matrice singulière, échec de LU avec pivot")
        
        # Permuter les lignes dans N et P
        permute(N, i, pivot_index)
        permute(P, i, pivot_index)

        # Calcul de U (ligne i)
        for j in range(i, n):
            somme = 0
            for k in range(i):
                somme += N[i][k] * N[k][j]
            N[i][j] = N[i][j] - somme
        
        # Calcul de L (colonne i)
        for j in range(i + 1, n):
            somme = 0
            for k in range(i):
                somme += N[j][k] * N[k][i]
            
            N[j][i] = (N[j][i] - somme) / N[i][i]
    
    return P, N


Vérifier la décomposition avec pivot sur un exemple de matrice carrée.


In [120]:
np.random.seed(42)

A = randomMatrix(SIZE)

P, N = MonLUPivot(A)

PA = P @ A

L, U = ExtractLU(N)

LU = L @ U

np.allclose(PA, LU) # On vérifie PA = LU

True

#### 4.3.2 Résoudre un système linéaire à l'aide de `MonLUPivot()`.


In [125]:
np.random.seed(42)

A = randomMatrix(SIZE)
print("A: \n", A, "\n")

P, N = MonLUPivot(A)

L, U = ExtractLU(N)
print("L: \n", L, "\n")
print("U: \n", U, "\n")

print("L @ U: \n", L @ U, "\n")


A: 
 [[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]
 [7 2 5 4]] 

L: 
 [[ 1.          0.          0.          0.        ]
 [ 0.85714286  1.          0.          0.        ]
 [ 0.85714286 -0.07692308  1.          0.        ]
 [ 1.         -0.35897436  0.40935673  1.        ]] 

U: 
 [[ 7.          4.          3.          7.        ]
 [ 0.          5.57142857 -0.57142857  0.        ]
 [ 0.          0.          4.38461538 -2.        ]
 [ 0.          0.          0.         -2.18128655]] 

L @ U: 
 [[7. 4. 3. 7.]
 [6. 9. 2. 6.]
 [6. 3. 7. 4.]
 [7. 2. 5. 4.]] 



In [122]:
print("L @ U: \n", L @ U, "\n")
print("A: \n", P @ A, "\n")

L @ U: 
 [[ 7.  4.  3.  7.]
 [42. 33. 20. 48.]
 [42. 51. 31. 64.]
 [49. 46. 60. 85.]] 

A: 
 [[7. 4. 3. 7.]
 [6. 9. 2. 6.]
 [6. 3. 7. 4.]
 [7. 2. 5. 4.]] 

